tcp:
  routers:
    postgres-direct:
      rule: "HostSNI(`*`)"
      entryPoints:
        - "postgres"
      service: "postgres-service"
  services:
    postgres-service:
      loadBalancer:
        servers:
          - address: "postgres:5432"
